# Generated by Django 3.0.8 on 2021-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0002_package_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package_details',
            old_name='p_price',
            new_name='p_price_per_person',
        ),
        migrations.AlterField(
            model_name='package_details',
            name='p_title',
            field=models.CharField(max_length=80),
        ),
    ]
