# Generated by Django 3.0.8 on 2021-04-08 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Package', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_msg', models.TextField(max_length=255)),
                ('f_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
